

import 'package:lyrics/Taieb/model/node_model.dart';
import 'package:lyrics/Taieb/provider/game_state.dart';
import 'package:flutter/material.dart';
List<NoteModel> mission1(){
  return [

    NoteModel(1,1,'',Colors.indigo),
    NoteModel(2,2,'',Colors.cyan),
    NoteModel(3,3,'',Colors.lightGreen),
    NoteModel(4,3,'',Colors.yellow),
    NoteModel(5,0,'',Colors.green),
    NoteModel(6,1,'',Colors.red),
    NoteModel(7,2,'',Colors.pink),
    NoteModel(8,3,'',Colors.indigo),
    NoteModel(9,2,'',Colors.grey),
    NoteModel(10,3,'',Colors.yellow),
    NoteModel(11,0,'',Colors.indigo),
    NoteModel(12,2,'',Colors.indigo),
    NoteModel(13,1,'',Colors.purple),
    NoteModel(14,3,'',Colors.indigo),
    NoteModel(15,0,'',Colors.red),
    NoteModel(16,1,'',Colors.indigo),
    NoteModel(17,2,'',Colors.lightGreen),
    NoteModel(18,3,'',Colors.indigo),
    NoteModel(19,2,'',Colors.yellow),
    NoteModel(20,3,'',Colors.indigo),
    NoteModel(21,1,'',Colors.pink),
    NoteModel(22,2,'',Colors.purple),
    NoteModel(23,1,'',Colors.blueGrey),
    NoteModel(24,3,'',Colors.indigo),
    NoteModel(25,0,'',Colors.red),
    NoteModel(26,1,'',Colors.indigo),
    NoteModel(27,2,'',Colors.green),
    NoteModel(28,3,'',Colors.indigo),
    NoteModel(29,2,'',Colors.indigo),
    NoteModel(30,3,'',Colors.red),
    NoteModel(31,1,'',Colors.grey),
    NoteModel(32,2,'',Colors.indigo),
    NoteModel(33,1,'',Colors.yellow),
    NoteModel(34,3,'',Colors.indigo),
    NoteModel(35,0,'',Colors.green),

    NoteModel(36,1,'',Colors.red),
    NoteModel(37,2,'',Colors.green),
    NoteModel(38,3,'',Colors.indigo),
    NoteModel(39,2,'',Colors.green),
    NoteModel(40,3,'',Colors.red),
    NoteModel(41,2,'',Colors.lightGreen),
    NoteModel(42,3,'',Colors.yellow),
    NoteModel(43,1,'',Colors.red),
    NoteModel(44,0,'',Colors.indigo),
    NoteModel(45,1,'',Colors.indigo),
    NoteModel(46,2,'',Colors.red),
    NoteModel(47,3,'',Colors.lightGreen),
    NoteModel(48,3,'',Colors.yellow),
    NoteModel(49,0,'',Colors.green),
    NoteModel(50,1,'',Colors.red),
    NoteModel(51,2,'',Colors.pink),
    NoteModel(52,3,'',Colors.indigo),
    NoteModel(53,2,'',Colors.grey),
    NoteModel(54,3,'',Colors.yellow),
    NoteModel(55,0,'',Colors.indigo),
    NoteModel(56,2,'',Colors.indigo),
    NoteModel(57,1,'',Colors.purple),
    NoteModel(58,3,'',Colors.indigo),
    NoteModel(59,0,'',Colors.red),
    NoteModel(60,1,'',Colors.indigo),
    NoteModel(61,2,'',Colors.lightGreen),
    NoteModel(62,3,'',Colors.indigo),
    NoteModel(63,2,'',Colors.yellow),
    NoteModel(64,3,'',Colors.indigo),
    NoteModel(65,1,'',Colors.pink),
    NoteModel(66,2,'',Colors.purple),
    NoteModel(67,1,'',Colors.blueGrey),
    NoteModel(68,3,'',Colors.indigo),
    NoteModel(69,0,'',Colors.red),
    NoteModel(70,1,'',Colors.indigo),
    NoteModel(71,2,'',Colors.green),
    NoteModel(72,3,'',Colors.indigo),
    NoteModel(73,2,'',Colors.indigo),
    NoteModel(74,3,'',Colors.red),
    NoteModel(75,1,'',Colors.grey),
    NoteModel(76,2,'',Colors.indigo),
    NoteModel(77,1,'',Colors.yellow),
    NoteModel(78,3,'',Colors.indigo),
    NoteModel(79,0,'',Colors.green),
    NoteModel(80,1,'',Colors.red),
    NoteModel(81,2,'',Colors.green),
    NoteModel(82,3,'',Colors.indigo),
    NoteModel(83,2,'',Colors.green),
    NoteModel(84,3,'',Colors.red),
    NoteModel(85,-1,'',Colors.lightGreen),
    NoteModel(86,-1,'',Colors.yellow),
    NoteModel(87,-1,'',Colors.red),
    NoteModel(88,-1,'',Colors.indigo),





  ];
}
