

import 'package:lyrics/Taieb/model/node_model.dart';
import 'package:flutter/material.dart';
import 'package:lyrics/Taieb/provider/game_state.dart';
List<NoteModel> mission5(){
  return [


    NoteModel(1,1,'',Colors.lightBlue),
    NoteModel(2,2,'',Colors.lightBlue),
    NoteModel(4,3,'',Colors.lightBlue),
    NoteModel(4,3,'',Colors.lightBlue),
    NoteModel(5,0,'',Colors.lightBlue),
    NoteModel(6,1,'',Colors.lightBlue),
    NoteModel(7,2,'START',Colors.lightBlue),
    NoteModel(8,3,'10',Colors.lightBlue),
    NoteModel(9,2,'7',Colors.lightBlue),
    NoteModel(10,3,'12',Colors.lightBlue),
    NoteModel(11,0,'13',Colors.lightBlue),
    NoteModel(12,2,'45',Colors.lightBlue),
    NoteModel(13,1,'47',Colors.lightBlue),
    NoteModel(14,3,'24',Colors.lightBlue),
    NoteModel(15,0,'50',Colors.lightBlue),
    NoteModel(16,1,'23',Colors.lightBlue),
    NoteModel(17,2,'25',Colors.lightBlue),
    NoteModel(18,3,'31',Colors.lightBlue),
    NoteModel(19,2,'46',Colors.lightBlue),
    NoteModel(20,3,'57',Colors.lightBlue),
    NoteModel(21,1,'43',Colors.lightBlue),
    NoteModel(22,2,'22',Colors.lightBlue),
    NoteModel(23,1,'10',Colors.lightBlue),
    NoteModel(24,3,'41',Colors.lightBlue),
    NoteModel(25,0,'7',Colors.lightBlue),
    NoteModel(26,1,'17',Colors.lightBlue),
    NoteModel(27,2,'9',Colors.lightBlue),
    NoteModel(28,3,'15',Colors.lightBlue),
    NoteModel(29,2,'3',Colors.lightBlue),
    NoteModel(30,3,'11',Colors.lightBlue),
    NoteModel(31,1,'18',Colors.lightBlue),
    NoteModel(32,2,'14',Colors.lightBlue),
    NoteModel(33,1,'22',Colors.lightBlue),
    NoteModel(34,3,'28',Colors.lightBlue),
    NoteModel(35,0,'2',Colors.lightBlue),

    NoteModel(36,1,'33',Colors.lightBlue),
    NoteModel(37,2,'27',Colors.lightBlue),
    NoteModel(38,3,'29',Colors.lightBlue),
    NoteModel(39,2,'1',Colors.lightBlue),
    NoteModel(40,3,'32',Colors.lightBlue),
    NoteModel(41,1,'8',Colors.lightBlue),
    NoteModel(42,2,'6',Colors.lightBlue),
    NoteModel(43,3,'5',Colors.lightBlue),
    NoteModel(44,0,'3',Colors.lightBlue),
    NoteModel(45,3,'10',Colors.lightBlue),
    NoteModel(46,2,'7',Colors.lightBlue),
    NoteModel(47,3,'12',Colors.lightBlue),
    NoteModel(48,0,'13',Colors.lightBlue),
    NoteModel(49,2,'45',Colors.lightBlue),
    NoteModel(50,1,'47',Colors.lightBlue),
    NoteModel(51,3,'24',Colors.lightBlue),
    NoteModel(52,0,'50',Colors.lightBlue),
    NoteModel(53,1,'23',Colors.lightBlue),
    NoteModel(54,2,'25',Colors.lightBlue),
    NoteModel(55,3,'31',Colors.lightBlue),
    NoteModel(56,2,'46',Colors.lightBlue),
    NoteModel(57,3,'57',Colors.lightBlue),
    NoteModel(58,1,'43',Colors.lightBlue),
    NoteModel(59,2,'22',Colors.lightBlue),
    NoteModel(60,1,'10',Colors.lightBlue),
    NoteModel(61,3,'41',Colors.lightBlue),
    NoteModel(62,0,'7',Colors.lightBlue),
    NoteModel(63,1,'17',Colors.lightBlue),
    NoteModel(64,2,'9',Colors.lightBlue),
    NoteModel(65,3,'15',Colors.lightBlue),
    NoteModel(66,2,'3',Colors.lightBlue),
    NoteModel(67,3,'11',Colors.lightBlue),
    NoteModel(68,1,'18',Colors.lightBlue),
    NoteModel(69,2,'14',Colors.lightBlue),
    NoteModel(70,1,'22',Colors.lightBlue),
    NoteModel(71,3,'28',Colors.lightBlue),
    NoteModel(72,0,'2',Colors.lightBlue),

    NoteModel(73,1,'33',Colors.lightBlue),
    NoteModel(74,2,'27',Colors.lightBlue),
    NoteModel(75,3,'29',Colors.lightBlue),
    NoteModel(76,2,'1',Colors.lightBlue),
    NoteModel(77,3,'32',Colors.lightBlue),
    NoteModel(78,-1,'8',Colors.lightBlue),
    NoteModel(79,-1,'6',Colors.lightBlue),
    NoteModel(80,-1,'5',Colors.lightBlue),
    NoteModel(81,-1,'3',Colors.lightBlue),





  ];
}
