

import 'package:lyrics/Taieb/model/node_model.dart';
import 'package:lyrics/Taieb/provider/game_state.dart';
import 'package:flutter/material.dart';
List<NoteModel> mission6(){
  return [

    NoteModel(1,1,'',Colors.lightBlue),
    NoteModel(2,2,'',Colors.lightBlue),
    NoteModel(4,3,'',Colors.lightBlue),
    NoteModel(4,3,'',Colors.lightBlue),
    NoteModel(5,0,'',Colors.lightBlue),
    NoteModel(6,1,'',Colors.lightBlue),
    NoteModel(7,2,'START',Colors.lightBlue),
    NoteModel(8,3,'Chien',Colors.lightBlue),
    NoteModel(9,2,'orange',Colors.lightBlue),
    NoteModel(10,3,'banane',Colors.lightBlue),
    NoteModel(11,0,'rouge',Colors.lightBlue),
    NoteModel(12,2,'Coq',Colors.lightBlue),
    NoteModel(13,1,'Pigeon',Colors.lightBlue),
    NoteModel(14,3,'blue',Colors.lightBlue),
    NoteModel(15,0,'chemise',Colors.lightBlue),
    NoteModel(16,1,'Singe',Colors.lightBlue),
    NoteModel(17,2,'Chameau',Colors.lightBlue),
    NoteModel(18,3,'ballon',Colors.lightBlue),
    NoteModel(19,2,'style',Colors.lightBlue),
    NoteModel(20,3,'macarena',Colors.lightBlue),
    NoteModel(21,1,'sky',Colors.lightBlue),
    NoteModel(22,2,'Oiseau',Colors.lightBlue),
    NoteModel(23,1,'appel',Colors.lightBlue),
    NoteModel(24,3,'cola',Colors.lightBlue),
    NoteModel(25,0,'Lapin',Colors.lightBlue),
    NoteModel(26,1,'service',Colors.lightBlue),
    NoteModel(27,2,'plus',Colors.lightBlue),
    NoteModel(28,3,'arbre',Colors.lightBlue),
    NoteModel(29,2,'mouss',Colors.lightBlue),
    NoteModel(30,3,'Rat',Colors.lightBlue),
    NoteModel(31,1,'romania',Colors.lightBlue),
    NoteModel(32,2,'Paris',Colors.lightBlue),
    NoteModel(33,1,'demande',Colors.lightBlue),
    NoteModel(34,3,'dimanche',Colors.lightBlue),
    NoteModel(35,0,'Zèbre',Colors.lightBlue),

    NoteModel(36,1,'car',Colors.lightBlue),
    NoteModel(37,2,'Cheval',Colors.lightBlue),
    NoteModel(38,3,'peace',Colors.lightBlue),
    NoteModel(39,2,'got',Colors.lightBlue),
    NoteModel(40,3,'harvey',Colors.lightBlue),
    NoteModel(41,2,'Pigeon',Colors.lightBlue),
    NoteModel(42,1,'Loup',Colors.lightBlue),
    NoteModel(43,3,'comme',Colors.lightBlue),
    NoteModel(44,0,'salad',Colors.lightBlue),
    NoteModel(45,3,'Chien',Colors.lightBlue),
    NoteModel(46,2,'orange',Colors.lightBlue),
    NoteModel(47,3,'banane',Colors.lightBlue),
    NoteModel(48,0,'rouge',Colors.lightBlue),
    NoteModel(49,2,'Coq',Colors.lightBlue),
    NoteModel(50,1,'Pigeon',Colors.lightBlue),
    NoteModel(51,3,'blue',Colors.lightBlue),
    NoteModel(52,0,'chemise',Colors.lightBlue),
    NoteModel(53,1,'Singe',Colors.lightBlue),
    NoteModel(54,2,'Chameau',Colors.lightBlue),
    NoteModel(55,3,'ballon',Colors.lightBlue),
    NoteModel(56,2,'style',Colors.lightBlue),
    NoteModel(57,3,'macarena',Colors.lightBlue),
    NoteModel(58,1,'sky',Colors.lightBlue),
    NoteModel(59,2,'Oiseau',Colors.lightBlue),
    NoteModel(60,1,'appel',Colors.lightBlue),
    NoteModel(61,3,'cola',Colors.lightBlue),
    NoteModel(62,0,'Lapin',Colors.lightBlue),
    NoteModel(63,1,'service',Colors.lightBlue),
    NoteModel(64,2,'plus',Colors.lightBlue),
    NoteModel(65,3,'arbre',Colors.lightBlue),
    NoteModel(66,2,'mouss',Colors.lightBlue),
    NoteModel(67,3,'Rat',Colors.lightBlue),
    NoteModel(68,1,'romania',Colors.lightBlue),
    NoteModel(69,2,'Paris',Colors.lightBlue),
    NoteModel(70,1,'demande',Colors.lightBlue),
    NoteModel(71,3,'dimanche',Colors.lightBlue),
    NoteModel(72,0,'Zèbre',Colors.lightBlue),

    NoteModel(73,1,'car',Colors.lightBlue),
    NoteModel(74,2,'Cheval',Colors.lightBlue),
    NoteModel(75,3,'peace',Colors.lightBlue),
    NoteModel(76,2,'got',Colors.lightBlue),
    NoteModel(77,3,'harvey',Colors.lightBlue),
    NoteModel(78,-1,'Pigeon',Colors.lightBlue),
    NoteModel(79,-1,'Loup',Colors.lightBlue),
    NoteModel(80,-1,'comme',Colors.lightBlue),
    NoteModel(81,-1,'salad',Colors.lightBlue),






  ];
}
