

import 'package:lyrics/Taieb/model/node_model.dart';
import 'package:lyrics/Taieb/provider/game_state.dart';
import 'package:flutter/material.dart';
List<NoteModel> mission7(){
  return [


    NoteModel(1,1,'',Colors.blueGrey),
    NoteModel(2,2,'',Colors.blueGrey),
    NoteModel(4,3,'',Colors.blueGrey),
    NoteModel(4,3,'',Colors.blueGrey),
    NoteModel(5,0,'',Colors.blueGrey),
    NoteModel(6,1,'',Colors.blueGrey),
    NoteModel(7,2,'START',Colors.blueGrey),
    NoteModel(8,3,'Chien',Colors.blueGrey),
    NoteModel(9,2,'orange',Colors.blueGrey),
    NoteModel(10,3,'banane',Colors.blueGrey),
    NoteModel(11,0,'rouge',Colors.blueGrey),
    NoteModel(12,2,'Coq',Colors.blueGrey),
    NoteModel(13,1,'Pigeon',Colors.blueGrey),
    NoteModel(14,3,'blue',Colors.blueGrey),
    NoteModel(15,0,'kiwi',Colors.blueGrey),
    NoteModel(16,1,'Singe',Colors.blueGrey),
    NoteModel(17,2,'abrico',Colors.blueGrey),
    NoteModel(18,3,'ballon',Colors.blueGrey),
    NoteModel(19,2,'style',Colors.blueGrey),
    NoteModel(20,3,'avocat',Colors.blueGrey),
    NoteModel(21,1,'sky',Colors.blueGrey),
    NoteModel(22,2,'Oiseau',Colors.blueGrey),
    NoteModel(23,1,'appel',Colors.blueGrey),
    NoteModel(24,3,'pomme',Colors.blueGrey),
    NoteModel(25,0,'fraise',Colors.blueGrey),
    NoteModel(26,1,'service',Colors.blueGrey),
    NoteModel(27,2,'plus',Colors.blueGrey),
    NoteModel(28,3,'arbre',Colors.blueGrey),
    NoteModel(29,2,'mouss',Colors.blueGrey),
    NoteModel(30,3,'mangue',Colors.blueGrey),
    NoteModel(31,1,'romania',Colors.blueGrey),
    NoteModel(32,2,'Paris',Colors.blueGrey),
    NoteModel(33,1,'demande',Colors.blueGrey),
    NoteModel(34,3,'dimanche',Colors.blueGrey),
    NoteModel(35,0,'Melon',Colors.blueGrey),

    NoteModel(36,1,'caramelle',Colors.blueGrey),
    NoteModel(37,2,'Cheval',Colors.blueGrey),
    NoteModel(38,3,'peace',Colors.blueGrey),
    NoteModel(39,2,'got',Colors.blueGrey),
    NoteModel(40,3,'harvey',Colors.blueGrey),
    NoteModel(41,2,'Pigeon',Colors.blueGrey),
    NoteModel(42,3,'poire',Colors.blueGrey),
    NoteModel(43,1,'comme',Colors.blueGrey),
    NoteModel(44,0,'salad',Colors.blueGrey),
    NoteModel(45,3,'Chien',Colors.blueGrey),
    NoteModel(46,2,'orange',Colors.blueGrey),
    NoteModel(47,3,'banane',Colors.blueGrey),
    NoteModel(48,0,'rouge',Colors.blueGrey),
    NoteModel(49,2,'Coq',Colors.blueGrey),
    NoteModel(50,1,'Pigeon',Colors.blueGrey),
    NoteModel(51,3,'blue',Colors.blueGrey),
    NoteModel(52,0,'kiwi',Colors.blueGrey),
    NoteModel(53,1,'Singe',Colors.blueGrey),
    NoteModel(54,2,'abrico',Colors.blueGrey),
    NoteModel(55,3,'ballon',Colors.blueGrey),
    NoteModel(56,2,'style',Colors.blueGrey),
    NoteModel(57,3,'avocat',Colors.blueGrey),
    NoteModel(58,1,'sky',Colors.blueGrey),
    NoteModel(59,2,'Oiseau',Colors.blueGrey),
    NoteModel(60,1,'appel',Colors.blueGrey),
    NoteModel(61,3,'pomme',Colors.blueGrey),
    NoteModel(62,0,'fraise',Colors.blueGrey),
    NoteModel(63,1,'service',Colors.blueGrey),
    NoteModel(64,2,'plus',Colors.blueGrey),
    NoteModel(65,3,'arbetraire',Colors.blueGrey),
    NoteModel(66,2,'mouss',Colors.blueGrey),
    NoteModel(67,3,'mangue',Colors.blueGrey),
    NoteModel(68,1,'romania',Colors.blueGrey),
    NoteModel(69,2,'Paris',Colors.blueGrey),
    NoteModel(70,1,'demande',Colors.blueGrey),
    NoteModel(71,3,'dimanche',Colors.blueGrey),
    NoteModel(72,0,'Melon',Colors.blueGrey),

    NoteModel(73,1,'caramelle',Colors.blueGrey),
    NoteModel(74,2,'Cheval',Colors.blueGrey),
    NoteModel(75,3,'peace',Colors.blueGrey),
    NoteModel(76,2,'got',Colors.blueGrey),
    NoteModel(77,3,'harvey',Colors.blueGrey),
    NoteModel(78,-1,'Pigeon',Colors.blueGrey),
    NoteModel(79,-1,'poire',Colors.blueGrey),
    NoteModel(80,-1,'comme',Colors.blueGrey),
    NoteModel(81,-1,'semi',Colors.blueGrey),





  ];
}
