

import 'package:lyrics/Taieb/model/node_model.dart';
import 'package:lyrics/Taieb/provider/game_state.dart';
import 'package:flutter/material.dart';
List<NoteModel> mission3(){
  return [

  NoteModel(1,0,'',Colors.amber),
  NoteModel(2,1,'',Colors.amber),
  NoteModel(3,2,'',Colors.amber),
  NoteModel(4,3,'',Colors.amber),
    NoteModel(5,0,'',Colors.amber),
    NoteModel(6,1,'',Colors.amber),
    NoteModel(7,2,'START',Colors.amber),
    NoteModel(8,3,'10',Colors.amber),
    NoteModel(9,2,'r',Colors.amber),
    NoteModel(10,3,'t',Colors.amber),
    NoteModel(11,0,'2',Colors.amber),
    NoteModel(12,2,'5',Colors.amber),
    NoteModel(13,1,'d',Colors.amber),
    NoteModel(14,3,'22',Colors.amber),
    NoteModel(15,0,'v',Colors.amber),
    NoteModel(16,1,'7',Colors.amber),
    NoteModel(17,2,'88',Colors.amber),
    NoteModel(18,3,'3',Colors.amber),
    NoteModel(19,2,'y',Colors.amber),
    NoteModel(20,3,'l',Colors.amber),
    NoteModel(21,1,'8',Colors.amber),
    NoteModel(22,2,'j',Colors.amber),
    NoteModel(23,1,'o',Colors.amber),
    NoteModel(24,3,'@',Colors.amber),
    NoteModel(25,0,'r',Colors.amber),
    NoteModel(26,1,'3',Colors.amber),
    NoteModel(27,2,'p',Colors.amber),
    NoteModel(28,3,'10',Colors.amber),
    NoteModel(29,2,'m',Colors.amber),
    NoteModel(30,3,'8',Colors.amber),
    NoteModel(31,1,'r',Colors.amber),
    NoteModel(32,2,'u',Colors.amber),
    NoteModel(33,1,'7',Colors.amber),
    NoteModel(34,3,'(',Colors.amber),
    NoteModel(35,0,'=',Colors.amber),

    NoteModel(36,1,'k',Colors.amber),
    NoteModel(37,2,'t',Colors.amber),
    NoteModel(38,3,'55',Colors.amber),
    NoteModel(39,2,'3',Colors.amber),
    NoteModel(40,3,'1',Colors.amber),
    NoteModel(41,2,'y',Colors.amber),
    NoteModel(42,3,'v',Colors.amber),
    NoteModel(43,2,'i',Colors.amber),
    NoteModel(44,1,'9',Colors.amber),
    NoteModel(45,3,'10',Colors.amber),
    NoteModel(46,2,'r',Colors.amber),
    NoteModel(47,3,'t',Colors.amber),
    NoteModel(48,0,'2',Colors.amber),
    NoteModel(49,2,'s',Colors.amber),
    NoteModel(50,1,'d',Colors.amber),
    NoteModel(51,3,'22',Colors.amber),
    NoteModel(52,0,'v',Colors.amber),
    NoteModel(53,1,'7',Colors.amber),
    NoteModel(54,2,'88',Colors.amber),
    NoteModel(55,3,'3',Colors.amber),
    NoteModel(56,2,'y',Colors.amber),
    NoteModel(57,3,'l',Colors.amber),
    NoteModel(58,1,'8',Colors.amber),
    NoteModel(59,2,'j',Colors.amber),
    NoteModel(60,1,'o',Colors.amber),
    NoteModel(61,3,'le',Colors.amber),
    NoteModel(62,0,'r',Colors.amber),
    NoteModel(63,1,'5',Colors.amber),
    NoteModel(64,2,'p',Colors.amber),
    NoteModel(65,3,'10',Colors.amber),
    NoteModel(66,2,'m',Colors.amber),
    NoteModel(67,3,'8',Colors.amber),
    NoteModel(68,1,'r',Colors.amber),
    NoteModel(69,2,'u',Colors.amber),
    NoteModel(70,1,'71',Colors.amber),
    NoteModel(71,3,'d',Colors.amber),
    NoteModel(72,0,'=',Colors.amber),

    NoteModel(73,1,'k',Colors.amber),
    NoteModel(74,2,'t',Colors.amber),
    NoteModel(75,3,'55',Colors.amber),
    NoteModel(76,2,'3',Colors.amber),
    NoteModel(77,3,'1',Colors.amber),
    NoteModel(78,-1,'y',Colors.amber),
    NoteModel(79,-1,'v',Colors.amber),
    NoteModel(80,-1,'i',Colors.amber),
    NoteModel(81,-1,'9',Colors.amber),


  ];
}
